# ============================================================================
#  EFPM makefile fragment
#  This is included by the top-level Makefile generated by configure.
# ============================================================================

efpm: $(SAPI_EFPM_PATH)

$(SAPI_EFPM_PATH): $(PHP_GLOBAL_OBJS) $(PHP_BINARY_OBJS) $(PHP_FASTCGI_OBJS) $(PHP_EFPM_OBJS)
	$(BUILD_EFPM)

install-efpm: $(SAPI_EFPM_PATH)
	@echo "Installing PHP EFPM binary:        $(INSTALL_ROOT)$(sbindir)/"
	@$(mkinstalldirs) $(INSTALL_ROOT)$(sbindir)
	@$(INSTALL) -m 0755 $(SAPI_EFPM_PATH) $(INSTALL_ROOT)$(sbindir)/$(program_prefix)php-efpm$(program_suffix)$(EXEEXT)
